// 1-FrontEnd/13-Svelte/A - Svelte basico/01-Reactive-Form/src/App.svelte
<script lang="ts">
  let name = "";
  let email = "";
  $: valid = name.trim().length >= 2 && email.includes("@");
</script>

<main class="container">
  <h1>01 - Reactive Form</h1>
  <div class="card" style="max-width:520px; display:grid; gap:10px;">
    <label>
      Nome
      <input bind:value={name} placeholder="Seu nome" style="width:100%; margin-top:6px; padding:10px; border-radius:8px; border:1px solid rgba(255,255,255,0.14); background:rgba(255,255,255,0.06); color:inherit;" />
    </label>
    <label>
      Email
      <input bind:value={email} placeholder="voce@exemplo.com" style="width:100%; margin-top:6px; padding:10px; border-radius:8px; border:1px solid rgba(255,255,255,0.14); background:rgba(255,255,255,0.06); color:inherit;" />
    </label>
    <button disabled={!valid}>Enviar</button>
    <div style="opacity:0.75">Valido: <strong>{valid ? "sim" : "nao"}</strong></div>
  </div>
</main>

// 1-FrontEnd/12-Zustand/B - Zustand avançado/03-Undo-Redo-History/src/App.tsx
import { useHistoryStore } from "./store";

export default function App() {
  const value = useHistoryStore((s) => s.present);
  const setValue = useHistoryStore((s) => s.set);
  const undo = useHistoryStore((s) => s.undo);
  const redo = useHistoryStore((s) => s.redo);
  const canUndo = useHistoryStore((s) => s.past.length > 0);
  const canRedo = useHistoryStore((s) => s.future.length > 0);

  return (
    <main className="container">
      <h1>Undo / Redo</h1>
      <div className="card" style={{ maxWidth: 520, display: "grid", gap: 10 }}>
        <input
          value={value}
          onChange={(e) => setValue(e.target.value)}
          placeholder="digite algo"
          style={{
            padding: 10,
            borderRadius: 8,
            border: "1px solid rgba(255,255,255,0.14)",
            background: "rgba(255,255,255,0.06)",
            color: "inherit"
          }}
        />
        <div style={{ display: "flex", gap: 8 }}>
          <button onClick={undo} disabled={!canUndo}>
            Undo
          </button>
          <button onClick={redo} disabled={!canRedo}>
            Redo
          </button>
        </div>
      </div>
    </main>
  );
}
