// 1-FrontEnd/13-Svelte/A - Svelte basico/01-Reactive-Form/src/App.svelte
<script lang="ts">
  let name = "";
  let email = "";
  $: valid = name.trim().length >= 2 && email.includes("@");
</script>

<main class="container">
  <h1>01 - Reactive Form</h1>
  <div class="card" style="max-width:520px; display:grid; gap:10px;">
    <label>
      Nome
      <input bind:value={name} placeholder="Seu nome" style="width:100%; margin-top:6px; padding:10px; border-radius:8px; border:1px solid rgba(255,255,255,0.14); background:rgba(255,255,255,0.06); color:inherit;" />
    </label>
    <label>
      Email
      <input bind:value={email} placeholder="voce@exemplo.com" style="width:100%; margin-top:6px; padding:10px; border-radius:8px; border:1px solid rgba(255,255,255,0.14); background:rgba(255,255,255,0.06); color:inherit;" />
    </label>
    <button disabled={!valid}>Enviar</button>
    <div style="opacity:0.75">Valido: <strong>{valid ? "sim" : "nao"}</strong></div>
  </div>
</main>

// 1-FrontEnd/12-Zustand/A - Zustand basico/03-User-Auth-State/src/App.tsx
import { useState } from "react";
import { useAuthStore } from "./store";

export default function App() {
  const user = useAuthStore((s) => s.user);
  const login = useAuthStore((s) => s.login);
  const logout = useAuthStore((s) => s.logout);
  const [email, setEmail] = useState("");

  return (
    <main className="container">
      <h1>03 - User Auth State</h1>
      <div className="card" style={{ maxWidth: 520, display: "grid", gap: 10 }}>
        {user ? (
          <>
            <div>
              Logado como <strong>{user.email}</strong>
            </div>
            <button onClick={logout}>Logout</button>
          </>
        ) : (
          <>
            <input
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="email"
              style={{
                padding: 10,
                borderRadius: 8,
                border: "1px solid rgba(255,255,255,0.14)",
                background: "rgba(255,255,255,0.06)",
                color: "inherit"
              }}
            />
            <button onClick={() => login(email.trim())} disabled={!email.trim()}>
              Login
            </button>
          </>
        )}
      </div>
    </main>
  );
}
