// 1-FrontEnd/13-Svelte/A - Svelte basico/03-Simple-Calculator/src/App.svelte
<script lang="ts">
  let a = 0;
  let b = 0;
  $: sum = a + b;
  $: diff = a - b;
  $: prod = a * b;
  $: div = b === 0 ? null : a / b;
</script>

<main class="container">
  <h1>03 - Simple Calculator</h1>
  <div class="card" style="max-width:520px; display:grid; gap:10px;">
    <label>
      A
      <input type="number" bind:value={a} style="width:100%; margin-top:6px; padding:10px; border-radius:8px; border:1px solid rgba(255,255,255,0.14); background:rgba(255,255,255,0.06); color:inherit;" />
    </label>
    <label>
      B
      <input type="number" bind:value={b} style="width:100%; margin-top:6px; padding:10px; border-radius:8px; border:1px solid rgba(255,255,255,0.14); background:rgba(255,255,255,0.06); color:inherit;" />
    </label>
    <div class="row">
      <div class="card"><strong>+</strong> {sum}</div>
      <div class="card"><strong>-</strong> {diff}</div>
      <div class="card"><strong>*</strong> {prod}</div>
      <div class="card"><strong>/</strong> {div ?? "inf"}</div>
    </div>
  </div>
</main>

// 1-FrontEnd/12-Zustand/A - Zustand basico/03-User-Auth-State/src/App.tsx
import { useState } from "react";
import { useAuthStore } from "./store";

export default function App() {
  const user = useAuthStore((s) => s.user);
  const login = useAuthStore((s) => s.login);
  const logout = useAuthStore((s) => s.logout);
  const [email, setEmail] = useState("");

  return (
    <main className="container">
      <h1>03 - User Auth State</h1>
      <div className="card" style={{ maxWidth: 520, display: "grid", gap: 10 }}>
        {user ? (
          <>
            <div>
              Logado como <strong>{user.email}</strong>
            </div>
            <button onClick={logout}>Logout</button>
          </>
        ) : (
          <>
            <input
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="email"
              style={{
                padding: 10,
                borderRadius: 8,
                border: "1px solid rgba(255,255,255,0.14)",
                background: "rgba(255,255,255,0.06)",
                color: "inherit"
              }}
            />
            <button onClick={() => login(email.trim())} disabled={!email.trim()}>
              Login
            </button>
          </>
        )}
      </div>
    </main>
  );
}
